
SET(BULLET_SEARCH_PATHS
	${USER_HOME}/source/polycode/Polycode/Release/${Linux}/Framework/Core/lib
	${USER_HOME}/source/polycode/Polycode/Release/${Linux}/Framework/Core/include
	${USER_HOME}/source/polycode/Polycode/Release/${Linux}/Framework/Modules/lib
	${USER_HOME}/source/polycode/Polycode/Release/${Linux}/Framework/Modules/include
)

# - Try to find Bullet
# Once done this will define
#
#  POLYCODE_FOUND - system has bullet
#  POLYCODE_INCLUDE_DIR - the bullet include directory
#  POLYCODE_LIBRARIES - Link these to use Collada DOM
#

FIND_PATH ( BULLET_INCLUDE_DIR NAMES btBulletCollisionCommon.h
	        HINTS
	        NO_DEFAULT_PATH
    	    NO_CMAKE_ENVIRONMENT_PATH
	        NO_CMAKE_SYSTEM_PATH
	        NO_SYSTEM_ENVIRONMENT_PATH
	        NO_CMAKE_PATH
	        CMAKE_FIND_FRAMEWORK NEVER
	        PATHS ${BULLET_SEARCH_PATHS} );

FIND_LIBRARY(LIBBULLETDYNAMICS
  NAMES 
  ${BULLETDYNAMICS}
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	CMAKE_FIND_FRAMEWORK NEVER
	$ENV{BULLETDIR}
	$ENV{BULLET_PATH}
	PATH_SUFFIXES lib lib64 win32/Dynamic_Release "Win32/${MSVC_YEAR_NAME}/x64/Release" "Win32/${MSVC_YEAR_NAME}/Win32/Release"
	PATHS ${BULLET_SEARCH_PATHS}
)

SET(BULLET_LIBRARIES ${LIBBULLETMULTITHREADED} ${LIBBULLETSOFTBODY} ${LIBBULLETDYNAMICS} ${LIBBULLETCOLLISION} ${LIBBULLETMATH})

SET(BULLET_LIBRARIES_DEBUG ${LIBBULLETMULTITHREADED_DEBUG} ${LIBBULLETSOFTBODY_DEBUG} ${LIBBULLETDYNAMICS_DEBUG} ${LIBBULLETCOLLISION_DEBUG} ${LIBBULLETMATH_DEBUG})

IF(BULLET_INCLUDE_DIR AND BULLET_LIBRARIES)
  SET(BULLET_FOUND TRUE)
ENDIF(BULLET_INCLUDE_DIR AND BULLET_LIBRARIES)

# show the BULLET_INCLUDE_DIR and BULLET_LIBRARIES variables only in the advanced view
IF(BULLET_FOUND)
  MESSAGE ("Bullet found (${BULLET_INCLUDE_DIR}) (${BULLET_LIBRARIES}) (${BULLET_LIBRARIES_DEBUG})")
  MARK_AS_ADVANCED(BULLET_INCLUDE_DIR BULLET_LIBRARIES BULLET_LIBRARIES_DEBUG)
ENDIF(BULLET_FOUND)

